package com.adaptiveapp.hestia.dal;

import com.adaptiveapp.hestia.model.ShopModel;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.Objects;

public interface ShopModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Feb 14 23:08:11 GMT 2024
     */
    int deleteByPrimaryKey(Integer id);

    Integer countAllShop();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Feb 14 23:08:11 GMT 2024
     */
    int insert(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Feb 14 23:08:11 GMT 2024
     */
    int insertSelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Feb 14 23:08:11 GMT 2024
     */
    ShopModel selectByPrimaryKey(Integer id);

    List<ShopModel>selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Feb 14 23:08:11 GMT 2024
     */
    int updateByPrimaryKeySelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Feb 14 23:08:11 GMT 2024
     */
    int updateByPrimaryKey(ShopModel record);
    List<ShopModel> recommend(@Param("longitude") BigDecimal logitude,
                              @Param("latitude") BigDecimal latitude);
    List<ShopModel> search(@Param("longitude") BigDecimal logitude,
                           @Param("latitude") BigDecimal latitude,
                           @Param("keyword") String keyword,
                           @Param("orderby") Integer orderby,
                           @Param("categoryId") Integer categoryId,
                           @Param("tags") String tags);

    List<Map<String, Object>> searchGroupByTags(@Param("keyword")String keyword,
                                                @Param("categoryId")Integer categoryId,
                                                @Param("tags")String tags);
}