package com.adaptiveapp.hestia.dal;

import com.adaptiveapp.hestia.model.UserModel;
import org.apache.ibatis.annotations.Param;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 11 02:19:27 GMT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 11 02:19:27 GMT 2024
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 11 02:19:27 GMT 2024
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 11 02:19:27 GMT 2024
     */
    UserModel selectByPrimaryKey(Integer id);

    //log in function
    UserModel selectByTelephoneAndPassword(@Param("telephone")String telephone, @Param("password")String password);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 11 02:19:27 GMT 2024
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 11 02:19:27 GMT 2024
     */
    int updateByPrimaryKey(UserModel record);

    Integer countAllUser();
}